## Esamina i Dati

Carichiamo i dati usando `read_csv` e diamo un'occhiata rapida con `head()`.

In [1]:
# Importing Libraries
import pandas as pd
import numpy as np
from datasets import load_dataset
import matplotlib.pyplot as plt  



# Carica il dataset
dataset = load_dataset("yiqing111/Engineering_Jobs_Insight_Dataset")
# Converte in DataFrame Pandas
df = dataset['train'].to_pandas()
# Rimpiazza gli spazi con l'underscore
df.columns = df.columns.str.replace(' ', '_')
# Convertire 'Date_Posted' in datetime senza specificare il formato esatto
df['Date_Posted'] = pd.to_datetime(df['Date_Posted'], errors='coerce')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Repo card metadata block was not found. Setting CardData to empty.

In [3]:
df.head()

,Job_Title,Company,Description,Location,Salary_Min,Salary_Max,Date_Posted,URL
0,Senior Software Engineer (Python),BP Energy,Entity: Trading & Shipping Job Family Group: S...,"Crestwood, Houston",138992.40,138992.40,2024-10-29 16:35:26+00:00,https://www.adzuna.com/land/ad/4917931721?se=N...
1,Sr. Backend Software Engineer,Meijer,"As a family company, we serve people and commu...","Belmont, Kent County",118638.80,118638.80,2024-11-10 01:13:11+00:00,https://www.adzuna.com/land/ad/4933370156?se=N...
2,Sr. Software Engineer - Mobile,Meijer,"As a family company, we serve people and commu...","Belmont, Kent County",108041.95,108041.95,2024-10-15 11:51:30+00:00,https://www.adzuna.com/land/ad/4902683574?se=N...
3,Acquisition Software Engineer,Naval Air Systems Command,Position Description The Harpoon/SLAM ER/JSOW ...,"China Lake, Kern County",88583.57,88583.57,2024-11-16 04:21:41+00:00,https://www.adzuna.com/land/ad/4941260438?se=N...
4,Senior Software Engineer,Innova,A client of Innova Solutions is immediately hi...,"Richardson, Dallas",121932.35,121932.35,2024-11-15 09:42:55+00:00,https://www.adzuna.com/details/4940271538?utm_...

## iloc

Abbiamo già imparato come ottenere le righe usando `iloc[]`.  
Ma possiamo fare molto di più con questo strumento: possiamo infatti selezionare *sia* righe *che* colonne.

Per fare questo, dobbiamo conoscere gli indici del nostro DataFrame.

In [4]:
df.iloc[0] #prima riga

Job_Title                      Senior Software Engineer (Python)
Company                                                BP Energy
Description    Entity: Trading & Shipping Job Family Group: S...
Location                                      Crestwood, Houston
Salary_Min                                              138992.4
Salary_Max                                              138992.4
Date_Posted                            2024-10-29 16:35:26+00:00
URL            https://www.adzuna.com/land/ad/4917931721?se=N...
Name: 0, dtype: object

##### Nota: usa `df.iloc[0, 15]` invece di `df.iloc[0][15]` per garantire la compatibilità futura con pandas.

L’uso dell’indicizzazione concatenata come `df.iloc[0][15]` è in fase di deprecazione in pandas, perché può portare a comportamenti ambigui tra accesso basato sulla posizione e accesso basato sull’etichetta nelle versioni future.  
Utilizzando `df.iloc[0, 15]`, specifichi direttamente la posizione dell’elemento che vuoi accedere, in modo più chiaro e sicuro, evitando potenziali errori futuri legati all’interpretazione degli indici interi nelle serie.

Quindi dovremmo scrivere:

In [4]:
df.iloc[0,5]

np.float64(138992.4)

In [6]:
df.iloc[2:4,4:6]

   Salary_Min  Salary_Max
2   108041.95   108041.95
3    88583.57    88583.57

In [9]:
df.iloc[[2,4],[2,5]]

                                         Description  Salary_Max
2  As a family company, we serve people and commu...   108041.95
4  A client of Innova Solutions is immediately hi...   121932.35

## loc

* `df.loc[]`: seleziona righe e colonne per **etichetta** o **intervallo di etichette**.
* È simile a `df.iloc[]`, ma consente di usare **etichette** invece degli indici numerici.

In [10]:
df.loc[:9,['Salary_Min',	'Salary_Max']]

   Salary_Min  Salary_Max
0   138992.40   138992.40
1   118638.80   118638.80
2   108041.95   108041.95
3    88583.57    88583.57
4   121932.35   121932.35
5   133348.23   133348.23
6    88769.20    88769.20
7    79830.78    79830.78
8    94173.15    94173.15
9    91324.85    91324.85

## Gestione dei Dati Mancanti


- `df.dropna()`: elimina i valori mancanti.

### Fillna

- `df.fillna()`: riempie i valori mancanti

In [5]:
data = {
    'Nome': ['Anna', 'Luca', 'Marco', 'Elisa'],
    'Età': [25, np.nan, 30, np.nan],
    'Città': ['Roma', 'Milano', np.nan, 'Torino']
}

df2 = pd.DataFrame(data)
df2

    Nome   Età   Città
0   Anna  25.0    Roma
1   Luca   NaN  Milano
2  Marco  30.0     NaN
3  Elisa   NaN  Torino

In [ ]:
df_drop = df2.dropna()
df_drop

   Nome   Età Città
0  Anna  25.0  Roma

In [ ]:
media_eta = df2['Età'].mean()
df2['Età'] = df2['Età'].fillna(media_eta)
df2

    Nome   Età   Città
0   Anna  25.0    Roma
1   Luca  27.5  Milano
2  Marco  30.0     NaN
3  Elisa  27.5  Torino

## Rimozione dei Duplicati

* `drop_duplicates()`: rimuove le righe duplicate.
* Gli analisti devono spesso ripulire i dati, e uno dei problemi più comuni che si incontrano sono i valori duplicati.

In [10]:
#Esempio
df = pd.DataFrame({
    'nome': ['Anna', 'Luca', 'Anna'],
    'eta': [20, 25, 20]
})

print(df)

# Rimozione duplicati
df_pulito = df.drop_duplicates()


print(df_pulito)

   nome  eta
0  Anna   20
1  Luca   25
2  Anna   20
   nome  eta
0  Anna   20
1  Luca   25

Fate attezione a come copiate il dataframe

In [7]:
# DataFrame Copy
df_original = df.copy()
df_altered = df_original

# Filling the missing values with the median salary
df_altered['Salary_Min'] = 5
df_altered['Salary_Min']

0        5
1        5
2        5
3        5
4        5
        ..
11180    5
11181    5
11182    5
11183    5
11184    5
Name: Salary_Min, Length: 11185, dtype: int64

In [11]:
df_original['Salary_Min']

0        5
1        5
2        5
3        5
4        5
        ..
11180    5
11181    5
11182    5
11183    5
11184    5
Name: Salary_Min, Length: 11185, dtype: int64

In [12]:
df['Salary_Min']

0        138992.40
1        118638.80
2        108041.95
3         88583.57
4        121932.35
           ...
11180    110000.00
11181    110000.00
11182    126635.63
11183    155731.52
11184    174527.50
Name: Salary_Min, Length: 11185, dtype: float64

In [13]:

print('ID of df_original:               ', id(df_original))
print('ID of df_altered:                ', id(df_altered))
print('ID of df:                        ', id(df))

ID of df_original:                6082430064
ID of df_altered:                 6082430064
ID of df:                         6059334528

## Campionamento

* `sample()`: estrae un campione casuale di elementi.

### Esempi

Otteniamo un campione casuale dei dati.  
È possibile ottenere un campione con un numero fisso di righe.

In [14]:
df.sample(n=2)

,Job_Title,Company,Description,Location,Salary_Min,Salary_Max,Date_Posted,URL
4574,Senior Product Manager,Public,About Public is an investing platform that mak...,"Grand Central, Manhattan",116118.54,116118.54,2024-11-23 08:53:13+00:00,https://www.adzuna.com/details/4948967317?utm_...
8469,Senior Site Reliability Engineer,Multi Media LLC,Multi Media LLC is a leader in digital innovat...,US,161000.00,180000.00,2024-08-12 15:32:27+00:00,https://www.adzuna.com/details/4822656797?utm_...

Oppure puoi selezionare casualmente una frazione dei dati (ad esempio, il 10% delle righe), con o senza reinserimento (replacement).

In [15]:
df.sample(frac=0.0005, replace=False) # (senza replacement) → ogni riga può essere selezionata una sola volta nel campione.

,Job_Title,Company,Description,Location,Salary_Min,Salary_Max,Date_Posted,URL
4219,Product Manager,CAPTRUST,WHO are we looking for? CAPTRUST is seeking an...,"North Hills, Wake County",89691.30,89691.30,2024-08-02 10:15:58+00:00,https://www.adzuna.com/details/4807212363?utm_...
2450,Lead Data Scientist,"Citibank, N.A.",The Lead Data Scientist is a strategic profess...,US,141440.00,212160.00,2024-11-09 05:31:21+00:00,https://www.adzuna.com/details/4932506435?utm_...
189,Real-Time Software Engineer,Boeing,The successful candidate will enjoy working in...,"Overland Park, Johnson County",89811.38,89811.38,2024-11-09 10:11:25+00:00,https://www.adzuna.com/land/ad/4932746560?se=D...
5194,Business Analyst,Quirch Foods,Responsibilities: Collaborate and work effecti...,"Coral Gables, Miami-Dade County",72478.26,72478.26,2024-10-30 14:15:47+00:00,https://www.adzuna.com/details/4918848987?utm_...
7579,DevOps Engineer (GitHub migration),Modus Create,Hello Are you ready to Work from Home and tran...,"Miami, Miami-Dade County",80054.31,80054.31,2024-08-02 05:42:07+00:00,https://www.adzuna.com/details/4807013832?utm_...
9821,Sr. Network Engineer,Concora Credit Inc.,Join the nation’s leader in second-look financ...,"Beaverton, Washington County",118751.20,118751.20,2024-05-17 09:48:43+00:00,https://www.adzuna.com/details/4697120884?utm_...

## Pandas Pivot 

È un'operazione che consente di ristrutturare un DataFrame, trasformando colonne in indici e viceversa. È utile quando vuoi riorganizzare i dati in una forma tabellare più leggibile o più adatta all’analisi.

In [15]:
df = pd.DataFrame({
    'Data': ['2024-01', '2024-01', '2024-02', '2024-02'],
    'Prodotto': ['A', 'B', 'A', 'B'],
    'Vendite': [100, 150, 120, 130]
})
df

      Data Prodotto  Vendite
0  2024-01        A      100
1  2024-01        B      150
2  2024-02        A      120
3  2024-02        B      130

In [16]:
# rioganizziamo i dati di modo che Le righe (index) siano le date, Le colonne, i prodotti, e le celle contengono i valori di vendite.

df.pivot(index='Data', columns='Prodotto', values='Vendite')

Prodotto    A    B
Data
2024-01   100  150
2024-02   120  130



- `pivot_table()` è una versione più flessibile di `pivot()`, perché ti permette di aggregare dati quando ci sono valori duplicati per la combinazione di indice e colonne.
* Syntax: `pivot_table(values='column_to_aggregate', index='row_index', columns='column_index', aggfunc='mean')`

In [17]:
df = pd.DataFrame({
    'Data': ['2024-01', '2024-01', '2024-01', '2024-02'],
    'Prodotto': ['A', 'A', 'B', 'B'],
    'Vendite': [100, 120, 150, 130]
})
df

      Data Prodotto  Vendite
0  2024-01        A      100
1  2024-01        A      120
2  2024-01        B      150
3  2024-02        B      130

In [18]:
df.pivot(index='Data', columns='Prodotto', values='Vendite')

ValueError: Index contains duplicate entries, cannot reshape

In [19]:
df.pivot_table(index='Data', columns='Prodotto', values='Vendite', aggfunc='sum')

Prodotto      A      B
Data
2024-01   220.0  150.0
2024-02     NaN  130.0

In [21]:
df.pivot_table(index='Prodotto', values='Vendite', aggfunc='sum')

          Vendite
Prodotto
A             220
B             280

In [ ]:
df.groupby('Prodotto')['Vendite'].sum()

Prodotto
A    220
B    280
Name: Vendite, dtype: int64

# Pandas `melt()`

Il metodo melt() di pandas serve per trasformare un DataFrame "largo" in uno "lungo" — cioè passare da colonne multiple a due colonne: una con i nomi delle variabili e una con i valori.

In [ ]:
df_short = pd.DataFrame({
    'Data': ['2024-01', '2024-02'],
    'A': [100, 150],
    'B': [120, 130]
})
df_short

      Data    A    B
0  2024-01  100  120
1  2024-02  150  130

In [ ]:
df_short.melt(id_vars = 'Data', var_name = 'Prodotto', value_name = 'Vendite')

      Data Prodotto  Vendite
0  2024-01        A      100
1  2024-02        A      150
2  2024-01        B      120
3  2024-02        B      130

## Esempio uso pivot

Contiamo quanti lavori per ogni tipo ci sono

In [ ]:
df.pivot_table(index='Job_Title', aggfunc='size').sort_values(ascending=False)

Job_Title
Software Engineer                                                     311
Product Manager  Social app startup                                   282
Associate Product Manager  Social app startup                         277
2025 Virtual Summer Intern Program - Product Analyst Intern (Xome)    267
Real-Time Software Engineer                                           266
                                                                     ...
Information Systems Security Engineer, Senior                           1
Information Systems Security Engineering (ISSE)                         1
Information Systems Security Officer/ Engineer                          1
Information Technology - Senior Business Analyst IT                     1
☁ Cloud HPC Engineer ☁                                                  1
Length: 4848, dtype: int64

In [ ]:
df.groupby('Job_Title').size().sort_values(ascending=False)

Job_Title
Software Engineer                                                     311
Product Manager  Social app startup                                   282
Associate Product Manager  Social app startup                         277
2025 Virtual Summer Intern Program - Product Analyst Intern (Xome)    267
Real-Time Software Engineer                                           266
                                                                     ...
Information Systems Security Engineer, Senior                           1
Information Systems Security Engineering (ISSE)                         1
Information Systems Security Officer/ Engineer                          1
Information Technology - Senior Business Analyst IT                     1
☁ Cloud HPC Engineer ☁                                                  1
Length: 4848, dtype: int64